spring:
  application:
    name: microservice-customer
  config:
    import: configserver:http://microservice-config:8888 #ruta y puerto del micro config server
  web:
    resources:
      add-mappings: false