server:
  port: 8091

spring:
  application:
    name: microservice-account
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/bank
    username: postgres
    password: '000000'
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: microservice-eureka
  client:
    service-url:
      defaultZone: http://microservice-eureka:8761/eureka